### ISSUE TITLE
Unable to get elements by tag name.

### ISSUE THREAD

**Issue by edwardvuong** [nfejzic/svg-morpher#1]
TypeError: fromSVG.getElementsByTagName is not a function

let fromPaths = Array.from(fromSVG.getElementsByTagName("path"));
let toPaths = Array.from(toSVG.getElementsByTagName("path"));

**Comment by nfejzic** [comment]
Hi, I'll take a look in following few days and try to resolve the issue.

**Comment by edwardvuong** [comment]
Thanks!

This might help:
I wrapped the contents inside of the function `morphFromTo()` to an event listener waiting for DOM content to be loaded. 
```
morphFromTo(fromSvgEl, toSvgEl, duration, callback) {
document.addEventListener('DOMContentLoaded', function(){ 
    let testTime = Date.now();
    let fromSVG = fromSvgEl;
    let testTime = Date.now();
    let fromSVG = fromSvgEl;
    let toSVG = toSvgEl;
    let fromPaths = Array.from(fromSVG.getElementsByTagName("path"));
    let toPaths = Array.from(toSVG.getElementsByTagName("path"));
    SVGMorpher.equalizeNumOfPaths(
      { parentSVG: fromSVG, paths: fromPaths },
      { parentSVG: toSVG, paths: toPaths }
    );
    SVGMorpher.animatePaths(
      { parentSVG: fromSVG, paths: fromPaths },
      { parentSVG: toSVG, paths: toPaths },
      duration,
      callback
    );
    SVGMorpher.animationDuration = Date.now() - testTime;
    if (this.animationDuration > 400) {
      this.animationResolution =
        this.animationResolution < 20 ? this.animationResolution + 1 : 20;
    } else if (this.animationDuration < 200) {
      this.animationResolution =
        this.animationResolution > 5 ? this.animationResolution - 1 : 5;
    }
 }, false);
},
```
This seems to fix the issue.
Running the code now and no errors appear to be present.
However, I'm not seeing the SVG being updated to the morphed content. 
Here's how I'm attempting to morph the SVG.

```
import React, { Component } from 'react';
import svg1 from './svg-1.svg';
import svg2 from './svg-2.svg';
import './App.css';
import SVGMorpher from "./SVGMorpher.js";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
        SVGImg: svg1,
    }
  }
  updateContent = () => {
      console.log('attempting SVG morph...');
      //morph SVG
      SVGMorpher.morphFromTo(svg1, svg2, 1.0);
      console.log('morphed!');
      //reload SVG image?? 
      this.setState({ SVGImg: svg1 });
  }
  render() {
    return (
      <div>
        <img src={this.state.SVGImg} className="App-logo" alt="logo" />
        <button onClick={this.updateContent}>
          SVG Morph!
        </button>
      </div>
    );
  }
}
export default App;
```

**Comment by nfejzic** [comment]
Ok, waiting for the content to be loaded is the correct solution. You can check my "zikrullah" repo to see how I've done my project with that. (It's some time ago, I don't remember all the details). 
Javascript does most of the stuff in async manner, so it tries to fetch something even though it hasn't loaded yet.

Does the SVG not morph at all? Try removing the part where you reset the svg element:

`this.setState({ SVGImg: svg1 });`

SVGMorpher changes the path values of the svg, so the original svg will be modified to look like the new svg, you should not reload it, except if you want it to revert back to the first svg after the animation.

Edit: Try the suggestion and let me know what happens.

**Comment by edwardvuong** [comment]
I got the image to morph. Except it's not rendering the image properly, but a morphing animation does occur. This might be because my SVG file has 240 d paths as well as 740 transforms. Regardless, all errors have been addressed and the image is morphing. Just not to be the desired result.

**Comment by nfejzic** [comment]
It also depends on what is the svg image exactly. I think it's really hard to get some svg with many colors and fills etc to behave as they should when morphing. I would suggest to try and make the svg as simple as possible.

If there are open areas, such a letter "O" for example, open up some SVG editing software and simply slice the letter, so that it's not fully closed. Otherwise in the morphing animation that O is going to be filled during animation, so it will simply look like a circle... 

I find SVG Morphing harder than it seems like...
